### ISSUE TITLE
Support WebSockets

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole-transit-relay#17]
In order to support magic-wormhole clients running in Web browsers, it would be useful to support connections from WebSocket clients (as well as "normal" TCP connections).

I don't believe this presents any technical challenges: a WebSocket client would send and receive bytes using the `onMessage` and `sendMessage` APIs in the browser while on the server side we could pass bytes between either TCP or WebSocket clients in a similar fashion.

Code-wise, I believe some re-factoring would be the best way to achieve this: move the "state machine" parts (of `Transit` / `TransitConnection`) to a common class that is used by both TCP and WebSocket implementations. I did take a stab at producing an [Automat](https://github.com/glyph/automat)-based state-machine (which Twisted depends on already) which has the side-benefit of also producing a state-machine.

I suppose there's also the question of "is this a good idea?" so perhaps it should be off by default (unless you add say `--websocket-endpoint` option).

**Comment by meejah** [comment]
It would be useful to have some high-level opinions here:

 - is websocket support a thing that should (ever) be supported?
 - is `Automat` the right state-machine hammer to use for this nail?

**Comment by piegamesde** [comment]
I think I can at least answer your first question with a confident *yes*.

**Comment by meejah** [comment]
The first step on the websockets journey is this PR (which could use a review): https://github.com/magic-wormhole/magic-wormhole-transit-relay/pull/20

(Not sure why codecov is confused but there is full patch coverage).

**Comment by meejah** [comment]
...but, yes, there seems to be consensus that _supporting websockets_ in general is a useful feature. Adding a command-line option to enable it seem reasonable. Otherwise I'm closing this -- I suppose opinions about the implementation are best expressed as reviews on pull-requests.
