### ISSUE TITLE
Documentation for setting up a relay server

### ISSUE THREAD

**Issue by con-f-use** [magic-wormhole/magic-wormhole-transit-relay#19]
Neither the readme nor readthedocs says how to set up a relay server. All I could find, was this issue comment: https://github.com/magic-wormhole/magic-wormhole/issues/288#issuecomment-373887259

**Comment by meejah** [comment]
Would be happy to accept @geerlingguy 's comment as a PR if you like :)

Can you say what weird problems you ran into specifying the relay on the receiving side? I believe it should work to specify a non-default relay on _either_ or _both_ sides.

**Comment by geerlingguy** [comment]
Yes, sorry about not having text, here is screenshots from the first attempt specifying on the receiving side:

![no-attribute-priority-2](https://github.com/magic-wormhole/magic-wormhole-transit-relay/assets/481677/8305f222-12a7-43e5-a8cb-7e2b938f873a)

On the second attempt there was another error... but I forgot to record or copy it out :(

**Comment by geerlingguy** [comment]
Also, just to note, I was able to get around 75 MB/sec on a DigitalOcean CPU-optimized droplet. On the public relay, the maximum I hit was around 40 MB/sec, but it would go down here and there (presumably when other people were using it).

Thanks so much for the public service :)

**Comment by meejah** [comment]
For the record, it is @warner who runs the public mailbox and transit-relay servers, but glad you appreciate them! :)
