### ISSUE TITLE
Python 3.5 and 3.6

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole-transit-relay#24]
The latest version of `autobahn` supports python 3.7+

version 20.12.13 dropped python 3.6 support
version 20.1.1 dropped python2 support

Not sure precisely when 3.5 was dropped. Main question here I guess is: do we want to stick with an old version of autobahn to maintain 3.5 and 3.6 support, or drop those as well?

**Comment by piegamesde** [comment]
Would there be any benefit in not dropping Python 3.5 / 3.6 support?

**Comment by meejah** [comment]
I cannot think of any .. I guess dropping this here in case some distribution that someone cares about ships 3.6 still...?
